# Copyright (c) 2022-2023 XiNGRZ
# SPDX-License-Identifier: MIT

description: |
  A virtual LED strip driver for reordering LEDs, with additional APIs for using
  individual LEDs as custom indicators.

compatible: "zmk,led-strip-remap"

properties:
  chain-length:
    type: int
    required: true
    description: The number of LEDs in the strip.
  led-strip:
    type: phandle
    required: true
  map:
    type: array
    required: true
    description: The re-ordered index of LEDs.

child-binding:
  description: Subset of LEDs to be use as indicators.
  properties:
    label:
      type: string
      required: true
    led-indexes:
      type: array
      required: true
      description: The indexes of the LEDs in the subset.
