# Copyright (c) 2022-2023 XiNGRZ
# SPDX-License-Identifier: MIT

description: A virtual display that rotates the frame by 90 degrees.

compatible: "zmk,display-sw-rotate"

include: display-controller.yaml

properties:
  display:
    type: phandle
    required: true

  buffer-lines:
    type: int
    default: 32
